Models/EntityModel/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DrivingSchool.Models.EntityModel
{
    public class Student
    {
        [Key]
        public int StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? GraduationDate { get; set; }

        public int AdmissionModeID { get; set; }
        [ForeignKey("AdmissionModeID")]
        public AdmissionMode AdmissionMode { get; set; }

        public int CarTypeID { get; set; }
        [ForeignKey("CarTypeID")]
        public CarType CarType { get; set; }

        public int InstructorID { get; set; }
        [ForeignKey("InstructorID")]
        public Instructor Instructor { get; set; }
    }
}

ViewModels/StudentViewModel.cs
using DrivingSchool.Models.EntityModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DrivingSchool.ViewModels
{
    public class StudentViewModel
    {
        public int StudentID { get; set; }
        [Required(ErrorMessage = "First name is required")]
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last name is required")]
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Address is required")]
        [DisplayName("Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "City is required")]
        [DisplayName("City")]
        public string City { get; set; }

        [BindProperty, DataType(DataType.PostalCode)]
        [Required(ErrorMessage = "Postal code is required")]
        [RegularExpression(@"^((([A-PR-UWYZ][0-9])|([A-PR-UWYZ][0-9][0-9])|([A-PR-UWYZ][A-HK-Y][0-9])|([A-PR-UWYZ][A-HK-Y][0-9][0-9])|([A-PR-UWYZ][0-9][A-HJKSTUW])|([A-PR-UWYZ][A-HK-Y][0-9][ABEHMNPRVWXY]))\s?([0-9][ABD-HJLNP-UW-Z]{2})|(GIR)\s?(0AA))$", ErrorMessage = "Not a valid postal code as \"LL00 0LL \" ")]
        
        [DisplayName("Poatal Code")]
        public string PostalCode { get; set; }

        [BindProperty, DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Phone is required")]
        [RegularExpression(@"^(?:(?:(?:00\s?|\+)44\s?|0)(?:1\d{8,9}|[23]\d{9}|7(?:[1345789]\d{8}|624\d{6})))$", ErrorMessage = "Not a valid phone number as \"+447888888883\"")]
        [DisplayName("Phone")]
        public string Phone { get; set; }

        [BindProperty, DataType(DataType.Date)]
        [Required(ErrorMessage = "Start date is required")]
        [DisplayName("Start Date")]
        public DateTime StartDate { get; set; }

        [BindProperty, DataType(DataType.Date)]
        [DisplayName("Gratiation Date")]
        public DateTime? GraduationDate { get; set; }

        public int AdmissionMode { get; set; }

        [Required(ErrorMessage = "Admission mode is required")]
        [DisplayName("Admission Mode")]
        public int AdmissionModeID { get; set; }
        [Required(ErrorMessage = "Car type is required")]
        [DisplayName("Car Type")]
        public int CarTypeID { get; set; }
        [Required(ErrorMessage = "Instructor is required")]
        [DisplayName("Instructor")]
        public int InstructorID { get; set; }

        private List<AdmissionMode> admissionModes;
        public List<AdmissionMode> AdmissionModes
        {
            get
            {
                return admissionModes;
            }
            set
            {
                admissionModes = new List<AdmissionMode>();
                admissionModes.AddRange(value);
            }
        }

        private List<CarType> carTypes;
        public List<CarType> CarTypes
        {
            get { return carTypes; }
            set
            {
                carTypes = new List<CarType>();
                carTypes.AddRange(value);
            }
        }

        private List<Instructor> instructors;
        public List<Instructor> Instructors
        {
            get { return instructors; }
            set
            {
                instructors = new List<Instructor>();
                instructors.AddRange(value);
            }
        }

    }
}

Controllers/StudentController.cs
using DrivingSchool.Models.Context;
using DrivingSchool.Models.EntityModel;
using DrivingSchool.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace DrivingSchool.Controllers
{
    public class StudentController : Controller
    {
        private DrivingSchoolDBContext context;
        private readonly ILogger<HomeController> _logger;
        // GET: StudentController

        public StudentController(ILogger<HomeController> logger, DrivingSchoolDBContext ctx)
        {
            _logger = logger;
            context = ctx;
        }

        public ActionResult Index()
        {
            return View();
        }

        // GET: StudentController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StudentController/Create
        public ActionResult Create()
        {
            ViewBag.Title = "Add Student data";
            StudentViewModel studentViewModel = new StudentViewModel();

            List<CarType> carTypes = context.CarTypes.ToList();
            List<AdmissionMode> admissionModes = context.AdmissionModes.ToList();
            List<Instructor> instructors = context.Instructors.ToList();

            studentViewModel.AdmissionModes = admissionModes;
            studentViewModel.CarTypes = carTypes;
            studentViewModel.Instructors = instructors;

            return View(studentViewModel);
        }

        // POST: StudentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StudentController/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.Title = "Edit Student data";
            var student = context.Students.Include(s => s.AdmissionMode)
                                        .Include(s => s.Instructor)
                                        .Include(s => s.CarType)
                                        .Where(s => s.StudentID == id).FirstOrDefault();
            if (student == null)
                student = new Student();

            StudentViewModel studentViewModel = new StudentViewModel();

            studentViewModel.StudentID = student.StudentID;
            studentViewModel.FirstName = student.FirstName;
            studentViewModel.LastName = student.LastName;
            studentViewModel.Address = student.Address;
            studentViewModel.City = student.City;
            studentViewModel.PostalCode = student.PostalCode;
            studentViewModel.Phone = student.Phone;
            studentViewModel.StartDate = student.StartDate;
            studentViewModel.GraduationDate = student.GraduationDate;
            studentViewModel.InstructorID = student.InstructorID;
            studentViewModel.CarTypeID = student.CarTypeID;
            studentViewModel.AdmissionModeID = student.AdmissionModeID;

            List<CarType> carTypes = context.CarTypes.ToList();
            List<AdmissionMode> admissionModes = context.AdmissionModes.ToList();
            List<Instructor> instructors = context.Instructors.ToList();

            studentViewModel.AdmissionModes = admissionModes;
            studentViewModel.CarTypes = carTypes;
            studentViewModel.Instructors = instructors;

            return View("Create", studentViewModel);
        }

        // POST: StudentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StudentViewModel studentViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var student = context.Students.Include(s => s.AdmissionMode)
                                           .Include(s => s.Instructor)
                                           .Include(s => s.CarType)
                                           .Where(s => s.StudentID == studentViewModel.StudentID).FirstOrDefault();

                    if (student == null)
                        student = new Student();

                    //Student student = new Student();
                    student.FirstName = studentViewModel.FirstName;
                    student.LastName = studentViewModel.LastName;
                    student.Address = studentViewModel.Address;
                    student.City = studentViewModel.City;
                    student.PostalCode = studentViewModel.PostalCode;
                    student.Phone = studentViewModel.Phone;
                    student.StartDate = studentViewModel.StartDate;
                    student.GraduationDate = studentViewModel.GraduationDate;
                    student.InstructorID = studentViewModel.InstructorID;
                    student.CarTypeID = studentViewModel.CarTypeID;
                    student.AdmissionModeID = studentViewModel.AdmissionModeID;

                    if (student.StudentID > 0)
                    {
                        context.SaveChanges();
                    }
                    else
                    {
                        context.Students.Add(student);
                    }
                    context.SaveChanges();

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("Invalid Model", "Invalid Model");
                    return View("Create", studentViewModel);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", "Error occured when saving.");
                return View("Create", studentViewModel);
            }
        }

        // GET: StudentController/Delete/5
        public ActionResult Delete(int id)
        {
            var student = context.Students.Include(s => s.AdmissionMode)
                                       .Include(s => s.Instructor)
                                       .Include(s => s.CarType)
                                       .Where(s => s.StudentID == id).FirstOrDefault();
            if (student != null)
            {
                context.Students.Remove(student);
                context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        // POST: StudentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Student/Create.cshtml
@using DrivingSchool.ViewModels;
@model StudentViewModel
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="createStudentForm">
            @using (Html.BeginForm("Edit", "Student",
FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "formStudent" }))
            {
                @Html.AntiForgeryToken()

                @Html.HiddenFor(m => m.StudentID)

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.City, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.City, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.PostalCode, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PostalCode, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Phone, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.StartDate, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">

                        <input type="date" name="StartDate" id="StartDate" value="@Model.StartDate.ToString("yyyy-MM-dd")" max="@DateTime.Now.ToString("yyyy-MM-dd")" />

                        @Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.GraduationDate, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                     

                        <input type="date" name="GraduationDate" id="GraduationDate" value="@Convert.ToDateTime(Model.GraduationDate).ToString("yyyy-MM-dd")" max="@DateTime.Now.ToString("yyyy-MM-dd")" />

                        @Html.ValidationMessageFor(m => m.GraduationDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.AdmissionMode, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.AdmissionModeID, new SelectList(Model.AdmissionModes, "AdmissionModeID", "AdmissionModeName"), "--Select Mode--")
                        @Html.ValidationMessageFor(m => m.AdmissionModeID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.CarTypeID, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.CarTypeID, new SelectList(Model.CarTypes, "CarTypeID", "CarTypeName"), "--Select Car Type--")
                        @Html.ValidationMessageFor(m => m.CarTypeID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.InstructorID, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.InstructorID, new SelectList(Model.Instructors, "InstructorID", "InstructorName"), "--Select Instructor--")
                        @Html.ValidationMessageFor(m => m.InstructorID, "", new { @class = "text-danger" })
                    </div>
                </div>




                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>

            }
        </section>
    </div>

</div>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script>
        $(document).ready(function () {

        });
    </script>
}